In [ ]:
!pip install tensorflow==2.15.0

In [4]:
!pip install scikit-learn tensorboard matplotlib streamlit scikeras

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 309.0 kB/s eta 0:00:001m677.8 kB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 839.4 kB/s eta 0:00:001.4 MB/s eta 0:00:01
  Using cached importlib_resources-6.4.0-py3-none-any.whl.metadata (3.9 kB)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
  Using cached tenacity-8.5.0-py3-none-any.whl.metadata (1.2 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.8/47.8 kB 2.1 MB/s eta 0:00:00
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 17.7 MB/s eta 0:00:00m eta 0:00:010:0101
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 17.7 MB/s eta 0:00:00m eta 0:00:010:00

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6186, 6775, 637, 4895],
 [6186, 6775, 637, 5462],
 [6186, 7872, 637, 7943],
 [7793, 3440, 840, 9701, 4879],
 [7793, 3440, 840, 9701, 1294],
 [932, 6186, 733, 637, 1731],
 [2258, 439, 5397, 9701]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6186 6775  637 4895]
 [   0    0    0    0 6186 6775  637 5462]
 [   0    0    0    0 6186 7872  637 7943]
 [   0    0    0 7793 3440  840 9701 4879]
 [   0    0    0 7793 3440  840 9701 1294]
 [   0    0    0  932 6186  733  637 1731]
 [   0    0    0    0 2258  439 5397 9701]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 75ms/step


array([[[ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [ 0.01453609,  0.03697893,  0.02267558,  0.01149287,
         -0.03695335,  0.01416664,  0.03655917,  0.00734384,
          0.03028754,  0.00339943],
        [-0.03792738,  0.01958679, -0.04232483, -0.03475742,
          0.02182527,  0.01143194, -0.03125288,  0.02584182,
          0.0050171 ,  0.04725457],
        [-0.02213118,  0.00730393,  0.02797868, -0.02386508,
         -0.0024281 ,  0.04419583, -0.02011771, -0.00502002,
         -0.03373672, -0.04126013],
        [-0.02629154,  0.02487988, -0.02824695,  0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6186, 6775,  637, 4895])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 19ms/step


array([[ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [ 0.01453609,  0.03697893,  0.02267558,  0.01149287, -0.03695335,
         0.01416664,  0.03655917,  0.00734384,  0.03028754,  0.00339943],
       [-0.03792738,  0.01958679, -0.04232483, -0.03475742,  0.02182527,
         0.01143194, -0.03125288,  0.02584182,  0.0050171 ,  0.04725457],
       [-0.02213118,  0.00730393,  0.02797868, -0.02386508, -0.0024281 ,
         0.04419583, -0.02011771, -0.00502002, -0.03373672, -0.04126013],
       [-0.02629154,  0.02487988, -0.02824695,  0.0302802 , -0.01835672,
        -0.00683415,  0.01606056, -0.04426531